### ISSUE TITLE
API for parsed maintenance times

### ISSUE THREAD

**Issue by Yandawl** [mattantonelli/lodestone#11]
Dear Raelys,

You are cordially invited (please) to create an API end point that will provide parsed maintenance JSON data including title, description & start/ end dates for Lodestone, the Companion App & FFXIV itself.

This will surely grant you our eternal love and undying gratitude.

Sincerely,
Lethys

**Comment by Yandawl** [comment]
THANK YOU

**Comment by mattantonelli** [comment]
Resolved by 02bdfe9
