### ISSUE TITLE
Endpoint that provides the most relevant maintenance for the different services

### ISSUE THREAD

**Issue by vekien** [mattantonelli/lodestone#12]
Hello,

Currently to get maintenance we will ping: http://na.lodestonenews.com/news/maintenance

This provides start and end times. 

A QOL endpoint would be one that just provides the most relevant (eg upcoming, or current) maintenance times for each of the major services: Companion, Game or Lodestone.

### Service Types

From what I can see, here are the types:

| Type | Post Title |
|--|--|
| `companion` | Companion App Maintenance |
| `lodestone` | The Lodestone Maintenance |
| `game` | All Worlds Maintenance |
| `mogstation` | Mog Station Maintenance |
| `support` | Support System Maintenance |
| `game_eu` / `game` | EU Data Center Emergency Maintenance |
| `game_na` / `game` | NA Data Center Emergency Maintenance |
| `game_jp` / `game` | All JP Worlds Emergency Maintenance |
| `account` | Square Enix Account Management System Maintenance |
| `psn` | "PSN" Maintenance "
| `forums` | FINAL FANTASY XIV Forums Maintenance |

Others we're not too concerned about:
- The Lodestone Login Function Emergency Maintenance

It would also be useful if "Emergency" could be detected.

### Example response:

```
{
  "companion": {
    "type": "companion",
    "title": "Companion App Maintenance",
    "start": "2019-07-30T07:00:00Z",
    "end": "2019-07-30T08:00:00Z",
    "is_emergency": false
  },
  "lodestone": null,
  "game": null,
  "mogstation" null
}
```

Each service is provided and if there is currently a maintenance time in the future or "now" (basically whenever "end" is in the future) it is added to the response. It would always provide the nearest end time to "now", so if there were 2 maintenance times listed for the same service (for whatever reason...) the earliest one would be listed.

### Use Case

People may have their own use case but it allows many services to automatically manage themselves based on the response. For example on Mogboard I could setup a 15 minute cronjob that requests this endpoint and if there is currently a `companion` maintenance it would auto pause the entire system until the end date.

**Comment by mattantonelli** [comment]
Resolved by b61f3715
