### ISSUE TITLE
RSS/Atom feed ?

### ISSUE THREAD

**Issue by kfdm** [mattantonelli/lodestone#16]
Do you think it would be in-scope to support RSS/Atom feeds for a URL ?

Example if I took `http://na.lodestonenews.com/news/maintenance` and added `.atom` or `.rss` it would provide a feed that I could view in a feed reader.

**Comment by mattantonelli** [comment]
I currently consider this project to be in maintenance mode, but I'll keep this request in mind if I ever get around to rebuilding the project.

**Comment by kfdm** [comment]
Understandable! Thank you for the response 😄

**Comment by liclac** [comment]
Would you accept a PR for it?

**Comment by mattantonelli** [comment]
I actually finished rebuilding the project earlier this year, so I do plan on taking a stab at this eventually, but I'm happy to take a look at a PR for it!

**Comment by liclac** [comment]
Ooh, exciting :eyes:
In that case, would it make more sense for me to do this on the rebuilt version, just so I don't have to do it twice?

**Comment by mattantonelli** [comment]
This is the rebuilt version, actually. 😄

**Comment by mattantonelli** [comment]
@kfdm @liclac let me know how this works for you: https://lodestonenews.com/feed/na.xml

You can swap out the `na` for any other region if you'd like.

**Comment by liclac** [comment]
Nice one, works for me!

I started working on this locally, but ran into some weird bugs (read: I'm not very good at Ruby), thank you for doing it in my stead :D

Can I filter it by category as well? The status messages are a bit spammy when put into an RSS reader.

**Comment by mattantonelli** [comment]
Each news item has a category, so you might be able to filter on that in your feed. Otherwise, I'd have to make a feed for each individual category, which would be a bit of a mess.

**Comment by kfdm** [comment]
> @kfdm @liclac let me know how this works for you: https://lodestonenews.com/feed/na.xml
> 
> You can swap out the `na` for any other region if you'd like.

Looks good! Thank you very much 🎉 🙇
