### ISSUE TITLE
[question] re-send article

### ISSUE THREAD

**Issue by Shuro** [mattantonelli/lodestone#7]
Hi mattantonelli,

quick question: My lodestone-instance died because I shutoff redis by accident. In the meantime there was a new post on Lodestone, which wasn't sent to my discord-server. Is there a possibility to resend the article?

Best regards,
Shuro

**Comment by mattantonelli** [comment]
You can verify if a post has been cached as sent by checking under the appropriate set of post IDs. For example, if you wanted to check on this morning's update about the letter from the producer: http://na.finalfantasyxiv.com/lodestone/topics/detail/048c164d0bff62ba78727b14f27bc125ecb65851

```
$ redis-cli
> sismember lodestone:topics-ids 048c164d0bff62ba78727b14f27bc125ecb65851
(integer) 1
```

This indicates that the post has been cached as sent to your subscribers. A value of 0 indicates that it has not. If you remove this ID from the cache, it will send the post again the next time it checks for updates.

```
> srem lodestone:topics-ids 048c164d0bff62ba78727b14f27bc125ecb65851
```

Keep in mind that if you had a partial send (e.g. it sent to some, then Redis shut down) your subscribers will receive duplicate posts. You can verify this in your logs and determine if it's worth the potential repost.

If you have more questions in the future, feel free to reach out to me by email: contact@raelys.com

**Comment by Shuro** [comment]
Thank you very much, that helped me a lot. I've noticed that I got the missing message some minutes later, probably because it rescanned for updates. Does it scan for new post since the latest previous post? Or does it depend on something else? What would happen if I stop the lodestone process today and restart it tomorrow?

**Comment by mattantonelli** [comment]
It fetches the latest news for each category every 30 mins. If it finds any post IDs in that data that don't exist in the sent cache, it sends out the updates to the subscribed webhooks and updates the cache. So if the process has been down, nothing will be sent, and the cache won't be updated. This means that when you bring the process back up it will see all of the posts you missed as "new" and send them out. 

The only way you can miss posts completely is if the process is down for so long that the posts are no longer on the first page of results on Lodestone. The posts would be significantly out of date at this point anyway.
